### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by WillNilges** [Mstrodl/clidrink#13]
![image](https://user-images.githubusercontent.com/42927786/158102336-c86de7a6-26a3-4a47-9bb6-1bd9b09a3fb9.png)

![image](https://user-images.githubusercontent.com/42927786/158102453-0d09b9c0-2e8b-4c5c-948d-2d5b6315860f.png)

![image](https://user-images.githubusercontent.com/42927786/158102477-6f8e4268-5de4-43ca-9f8c-7da095e5ba8f.png)

Er, well, I _want_ a logo. I have a few ideas.

**Comment by WillNilges** [comment]
I always think of these lil' whiskey glasses whenever I hear the name, "clink."

**Comment by adryd325** [comment]
Created a vector based on the cursive sketch ![bitmap](https://user-images.githubusercontent.com/48024900/190052597-557fedb2-f30b-4336-8444-4c93415d7300.png)

**Comment by Mstrodl** [comment]
Fixed in #22
